name: riverpod_firebase_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  hooks_riverpod: ^2.3.2
  pedantic_mono: ^1.21.1
  flutter_spinkit: ^5.1.0
  connectivity_plus: ^3.0.3
  gap: ^2.0.1
  flutter_hooks: ^0.18.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttc
